language: python

python:
  - "3.5"

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings.travis
  - export DATABASE_URL=postgres:///votacao-test

# comando para instalar dependencias
install: 
  - pip install -r requirements.txt
  - pip install codecov

#before_script:
#  - psql -c 'create database mscmctest;' -U postgres
#  - python manage.py makemigrations api
#  - python manage.py migrate api

# comando para rodas os testes
script: 
  - coverage run manage.py test

after_success:
  codecov