language: python

python:
  - "3.5"

services: postgresql

env:
  MSCMC_SERVER=https://mscmc-staging.cmc.pr.gov.br
  DATABASE_TEST_URL=postgres:///votacao-test

before_install:
  - export DJANGO_SETTINGS_MODULE=config.settings.travis
  - export DATABASE_URL=postgres:///votacao-test
  - sudo apt-get install -y libenchant-dev  
  - sudo apt-get install -y libenchant1c2a

# comando para instalar dependencias
install: 
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  #- python manage.py makemigrations autentica core --settings=config.settings.travis
  #- python manage.py migrate --settings=config.settings.travis  

#before_script:
#  - psql -c 'create database mscmctest;' -U postgres
#  - python manage.py makemigrations api
#  - python manage.py migrate api

# comando para rodas os testes
script: 
  - coverage run manage.py test --settings=config.settings.travis

after_success:
  codecov